FROM python:3.14.3-slim

# evitar archivos pyc
ENV PYTHONDONTWRITEBYTECODE=1

# mostrar logs directamente
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev

# copiar requirements
COPY requirements.txt .

# instalar dependencias python
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copiar proyecto
COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]